Repository VoxelForge/VoxelForge, pull requests merged in 2024-07, with the labels that each got.

#49 fix vlf_entity_effects images not loading
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_arrow_inv.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_blindness_hud.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_dragon_breath.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_absorbtion.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_absorption.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_bad_luck.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_bad_omen.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_blindness.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_conduit_power.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_darkness.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_dolphin_grace.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_fatigue.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_fire_proof.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_fire_resistance.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_food_poisoning.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_frost.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_glowing.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_haste.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_health_boost.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_hero_of_village.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_invisibility.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_invisible.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_leaping.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_levitation.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_luck.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_nausea.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_night_vision.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_poison.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_poisoned.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_regenerating.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_regeneration.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_resistance.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_saturation.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_slow.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_slow_falling.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_slowness.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_strength.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_strong.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_swift.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_swiftness.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_water_breathing.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_weak.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_weakness.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_effect_withering.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_entity_effect_bottle.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_entity_effect_overlay.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_frost_hud.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_glow_waypoint.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_icon_absorb.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_icon_frost.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_icon_regen_frost.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_icon_regen_wither.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_icon_wither.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_lingering_bottle.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_melon_speckled.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_spider_eye_fermented.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_splash_bottle.png
  mods/CORE/vlf_textures/textures/PP/block/vlf_entity_effects_splash_overlay.png
Labels: bug, One Approval, Trivial, Visual/Shaders, P7: Priority Roadmap

#53 fix sqlite database running out of memory when spawning villages
  mods/CORE/vlf_util/init.lua
  mods/ENTITIES/mobs_mc/villager.lua
  mods/ENTITIES/mobs_mc/villagers/trades.lua
  mods/ENTITIES/mobs_mc/villagers/wandering_trader.lua
  mods/MAPGEN/vlf_villages/foundation.lua
Labels: bug, One Approval, Trivial, P6: Critical

#55 debundle vlf_music to improve default performance.
  API.md
  Sound_License.txt
  menu/theme.1.ogg
  menu/theme.ogg
  mods/PLAYER/vlf_music/init.lua
  mods/PLAYER/vlf_music/locale/mcl_music.de.tr
  mods/PLAYER/vlf_music/locale/mcl_music.fr.tr
  mods/PLAYER/vlf_music/locale/mcl_music.pt_BR.tr
  mods/PLAYER/vlf_music/locale/mcl_music.ru.tr
  mods/PLAYER/vlf_music/locale/template.txt
  mods/PLAYER/vlf_music/mod.conf
  mods/PLAYER/vlf_music/sounds/calm1.ogg
  mods/PLAYER/vlf_music/sounds/calm2.ogg
  mods/PLAYER/vlf_music/sounds/calm3.ogg
  mods/PLAYER/vlf_music/sounds/end.ogg
  mods/PLAYER/vlf_music/sounds/hal1.ogg
  mods/PLAYER/vlf_music/sounds/hal2.ogg
  mods/PLAYER/vlf_music/sounds/hal3.ogg
  mods/PLAYER/vlf_music/sounds/hal4.ogg
  mods/PLAYER/vlf_music/sounds/music_license.md
  mods/PLAYER/vlf_music/sounds/nether1.ogg
  mods/PLAYER/vlf_music/sounds/nether2.ogg
  mods/PLAYER/vlf_music/sounds/nether3.ogg
  mods/PLAYER/vlf_music/sounds/nether4.ogg
  mods/PLAYER/vlf_music/sounds/nuance1.ogg
  mods/PLAYER/vlf_music/sounds/nuance2.ogg
  mods/PLAYER/vlf_music/sounds/piano1.ogg
  mods/PLAYER/vlf_music/sounds/piano2.ogg
  mods/PLAYER/vlf_music/sounds/piano3.ogg
Labels: P5: Very High Priority, Trivial, Audio/Textures

#71 Bug fixes
  menu/footer.png
  mods/ENTITIES/mobs_mc/models/mobs_mc_villager.b3d
  mods/ENTITIES/vlf_charges/init.lua
  mods/ENTITIES/vlf_mobs/breeding.lua
  mods/HUD/vlf_credits/people.lua
  mods/ITEMS/vlf_sus_stew/init.lua
  mods/ITEMS/vlf_tools/init.lua
  mods/PLAYER/vlf_player/init.lua
Labels: bug, Trivial, P6: Critical

#75 More Bug fixes
  menu/footer.png
  mods/CORE/vlf_textures/textures/voxelforge/hud/underwater_overlay.png
  mods/EFFECTS/vlf_effects/functions.lua
Labels: bug, P3: Priority Elevated, Trivial, Audio/Textures, Visual/Shaders

#76 Bug fixes
  mods/ITEMS/vlf_tools/init.lua
Labels: bug, P4: Priority High, Trivial

#77 even more bug fixes
  mods/CORE/vlf_schematics/schems/vlf_structures_end_portal_room_simple.mts
  mods/CORE/vlf_util/init.lua
  mods/MAPGEN/vlf_strongholds/init.lua
Labels: bug, enhancement, P3: Priority Elevated, Trivial, Biome/Structures

#82 fix tropical fish collision box
  mods/ENTITIES/mobs_mc/tropical_fish.lua
Labels: bug, P2: Priority Medium, Trivial, Upstream

#90 Tripwire.
  .luacheckrc
  mods/ITEMS/vlf_copper/nodes.lua
  mods/ITEMS/vlf_mobitems/init.lua
  mods/ITEMS/vlf_trials/api.lua
  mods/ITEMS/vlf_tripwire/LICENSE
  mods/ITEMS/vlf_tripwire/README.MD
  mods/ITEMS/vlf_tripwire/init.lua
  mods/ITEMS/vlf_tripwire/mod.conf
  mods/ITEMS/vlf_tripwire/models/texture.png
  mods/ITEMS/vlf_tripwire/models/tripwire_hook.mtl
  mods/ITEMS/vlf_tripwire/models/tripwire_hook.obj
  mods/ITEMS/vlf_tripwire/models/tripwire_hook_on.mtl
  mods/ITEMS/vlf_tripwire/models/tripwire_hook_on.obj
  mods/ITEMS/vlf_tripwire/textures/tripwire.png
  mods/ITEMS/vlf_tripwire/textures/tripwire_hook.png
  mods/ITEMS/vlf_tripwire/textures/tripwire_hook_on.png
Labels: enhancement, P2: Priority Medium, Trivial, Audio/Textures
